version: '3.8'
services:
  dev:
    build:
      context: ../backend
      dockerfile: ../.devcontainer/Dockerfile
    command: sleep infinity
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ..:/workspace:cached

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
